import { Content, LocalizedString, CalculatorContent } from '../types';

export const content: Content = {
  nav: {
    home: { en: 'Home', ar: 'الرئيسية' },
    about: { en: 'About us', ar: 'من نحن' },
    shipWithUs: { en: 'Ship with us', ar: 'اشحن معنا' },
    trackOrder: { en: 'Track Order', ar: 'تتبع الطلب' },
    terms: { en: 'Terms of Use', ar: 'شروط الإستخدام' },
    privacy: { en: 'Privacy Policy', ar: 'سياسة الخصوصية' },
    shippingCalculator: { en: 'Shipping Calculator', ar: 'حاسبة الشحن' },
    orderNow: { en: 'Order Now', ar: 'اطلب الآن' },
    contact: { en: 'Contact us', ar: 'إتصل بنا' },
  },
  home: {
    learnMore: { en: 'Learn More', ar: 'اعرف المزيد' },
    deliveryAreas: {
      title: { en: 'We Deliver To:', ar: 'نحن نوصل إلى:' },
      cities: [
        { en: 'Cairo', ar: 'القاهرة' },
        { en: 'Giza', ar: 'الجيزة' },
        { en: 'Alexandria', ar: 'الإسكندرية' },
        { en: 'Tanta', ar: 'طنطا' },
        { en: 'Mansoura', ar: 'المنصورة' },
      ]
    }
  },
  about: {
    title: { en: 'About Us', ar: 'من نحن' },
    p1: { en: 'At THE FAST BIRD, we believe that fast and safe shipping is the foundation of customer satisfaction and partner trust.', ar: 'نحن في THE FAST BIRD نؤمن أن الشحن السريع والآمن هو أساس رضا العميل وثقة الشركاء.' },
    p2: { en: 'Established in 2020, THE FAST BIRD is your first choice for shipping services within Egypt, offering smart solutions and advanced technologies to combine speed, security, and a professional customer experience.', ar: 'تأسست THE FAST BIRD في عام 2020 لتكون خيارك الأول في خدمات الشحن داخل مصر، عبر حلول ذكية وتقنيات متطورة نجمع بها بين السرعة، والأمان، وتجربة العميل الاحترافية.' },
    visionTitle: { en: 'Our Vision', ar: 'رؤيتنا' },
    visionText: { en: 'To elevate the shipping experience to a new standard of ease and service quality, becoming leaders in parcel shipping with efficiency and sustainability that meets our customers\' aspirations in the age of speed.', ar: 'أن نرتقي بتجربة الشحن إلى معيار جديد من السهولة وجودة الخدمات، لنكون الروّاد في مجال شحن الطرود بكفاءة واستدامة تُلبي تطلعات عملائنا في عصر السرعة.' },
    servicesTitle: { en: 'Our Services', ar: 'خدماتنا' },
    servicesText: { en: 'Shipping all types of parcels (clothes, electronics, spare parts, gifts, documents, etc.)\nSpecialized secure packaging for fragile items\nLive tracking via the website with a unique code for each shipment\nFast customer support via chat with "Barq - The Smart Bird"\nDoor-to-door delivery within all of Cairo, Giza, Alexandria, Tanta, and Mansoura', ar: 'شحن الطرود بجميع أنواعها: (ملابس – إلكترونيات – قطع غيار – هدايا – مستندات – إلى آخره)\nتغليف آمن متخصص للطرد القابل للكسر\nتتبع مباشر عبر الموقع بكود فريد لكل شحنة\nدعم عملاء سريع عبر الدردشة مع “برق - الطائر الذكي”\nتوصيل باب - لباب داخل كافة القاهرة، الجيزة، الإسكندرية، طنطا والمنصورة' },
    valuesTitle: { en: 'Our Values', ar: 'قيمنا' },
    valuesText: { en: 'Speed: Your time is precious, and we race against it for you\nCredibility: We are committed to clarity and transparency in our schedules and services\nSecurity: We protect your shipment with all means because it is our shipment\nInnovation: We adopt the latest AI solutions to facilitate and speed up the service', ar: 'السرعة: وقتك ثمين ونسابق الزمن من أجلك\nالمصداقية: نلتزم بالوضوح والشفافية في مواعيدنا وخدماتنا\nالأمان: نحمي شحنتك بكل الوسائل لأنها شحنتنا\nالابتكار: نعتمد أحدث حلول الذكاء الاصطناعي لتسهيل وتسريع الخدمة' },
    whyUsTitle: { en: 'Why Choose Us?', ar: 'لماذا تختارنا؟' },
    whyUsText: { en: 'Track your shipment moment by moment with a special code\nContinuous customer service and a smart chatbot that responds instantly\nCompetitive and transparent pricing\nExpertise of a dedicated team in shipping and packaging\nFlexible delivery options and special packaging for fragile items', ar: 'متابعة شحنتك لحظة بلحظة بكود خاص\nخدمة عملاء متواصلة وشات بوت ذكي يجيب فورياً\nأسعار تنافسية وشفافية كاملة\nخبرة فريق متكامل في الشحن والتغليف\nخيارات توصيل مرنة وتغليف خاص للطرد القابل للكسر' },
    missionTitle: { en: 'Our Mission', ar: 'رسالتنا' },
    missionText: { en: 'We aspire to be the wing that delivers your dreams and goods in the fastest time with the best shipping experience, through advanced technology and a team that cares about every detail.', ar: 'نطمح لأن نكون الجناح الذي يوصل أحلامك وبضائعك بأسرع وقت وأفضل تجربة شحن، عبر تكنولوجيا متقدمة وفريق يهتم بكل التفاصيل.' },
    ctaTitle: { en: 'Have a question or need help?', ar: 'لديك سؤال أو تحتاج مساعدة؟' },
    ctaText: { en: 'Talk to Barq, your smart bird, via the chat window or order your shipment now!', ar: 'كلّم برق طائرك الذكي عبر نافذة الشات أو اطلب شحنتك الآن!' },
  },
  shipWithUs: {
    title: { en: 'Ship With Us', ar: 'اشحن معنا'},
    subtitle: { en: 'We provide the best shipping services with full commitment to deadlines and safety.', ar: 'نوفر لك أفضل خدمات الشحن مع الالتزام التام بالمواعيد والأمان.'},
    pageTitle: { en: 'Simple, Fast, and Secure Shipping', ar: 'شحن بسيط، سريع، وآمن' },
    pageSubtitle: { en: 'Looking for an easy and fast way to ship your parcels safely?', ar: 'هل تبحث عن طريقة سهلة وسريعة لشحن طرودك بأمان؟' },
    pageSubtitle2: { en: 'With THE FAST BIRD, everything is simple and clear from the first step to door-to-door delivery!', ar: 'مع THE FAST BIRD، كل شيء بسيط وواضح من أول خطوة حتى توصيل الطرد للباب!' },
    howItWorks: { en: 'Four Simple Steps to Ship With Us', ar: 'أربع خطوات بسيطة للشحن معنا' },
    step1Title: { en: 'Submit Your Order', ar: 'تقديم الطلب' },
    step1Text: { en: 'Submit your order through our website and get an instant tracking code.', ar: 'قدم طلبك عبر موقعنا واحصل على كود التتبع الفوري.' },
    step2Title: { en: 'Shipment Pickup', ar: 'استلام الشحنة' },
    step2Text: { en: 'We pick up your shipment from your address at the scheduled time.', ar: 'نستلم شحنتك من عنوانك في الوقت المحدد.' },
    step3Title: { en: 'Track Your Shipment', ar: 'تتبع الشحنة' },
    step3Text: { en: 'Follow your shipment every step of the way with the tracking code.', ar: 'تابع شحنتك في كل خطوة عبر كود التتبع.' },
    step4Title: { en: 'Delivery', ar: 'التسليم' },
    step4Text: { en: 'We deliver your shipment to the recipient on the scheduled date.', ar: 'نسلم شحنتك للمستلم في الموعد المحدد.' },
    whyChooseUsTitle: { en: 'Why Choose The Fast Bird?', ar: 'لماذا تختار الطائر السريع؟' },
    reason1: { en: 'Full commitment to deadlines... your shipment always arrives on time.', ar: 'الالتزام التام في المواعيد... شحنتك توصل في الوقت المحدد دائماً.' },
    reason2: { en: 'Accuracy and security in every step — your shipment is like our own.', ar: 'دقة وأمان في كل خطوة — شحنتك كأنها شحنتنا.' },
    reason3: { en: 'Exceptional service and quick communication from the moment you order until delivery.', ar: 'خدمة استثنائية وتواصل سريع معك من لحظة الطلب حتى استلام الشحنة.' },
    reason4: { en: 'Our prices are competitive... the best service at the lowest cost, with no hidden fees.', ar: 'أسعارنا منافسة... أفضل خدمة بأقل تكلفة، بدون أي رسوم خفية.' },
    reason5: { en: 'Easily track your shipment with the instant tracking code.', ar: 'متابعة شحنتك بسهولة تامة مع كود التتبع الفوري.' },
    ctaTitle: { en: 'Ready to Ship?', ar: 'جاهز تشحن؟' },
    ctaText: { en: 'Start your journey now with THE FAST BIRD... the fastest wing for your parcels!', ar: 'ابدأ رحلتك الآن مع THE FAST BIRD... الجناح الأسرع لطرودك!' },
    ctaButton: { en: 'Order Now', ar: 'اطلب الآن' },
  },
  terms: {
    title: { en: 'Terms of Use', ar: 'شروط الإستخدام' },
    t1title: { en: 'Acceptance of Terms', ar: 'قبول الشروط' },
    t1text: { en: 'By using the THE FAST BIRD website or services, you automatically agree to all the terms and conditions on this page.', ar: 'عند استخدامك لموقع أو خدمات THE FAST BIRD، فأنت توافق تلقائياً على جميع الشروط والأحكام الواردة في هذه الصفحة.' },
    t2title: { en: 'Shipping Services', ar: 'خدمات الشحن' },
    t2text: { en: 'THE FAST BIRD provides various parcel shipping services within Egypt to the end customer according to the conditions for each shipment type. The company reserves the right to refuse to ship any legally prohibited content or content that does not comply with approved safety policies.', ar: 'يقدم “THE FAST BIRD” خدمات شحن الطرود بأنواعها داخل مصر للعميل النهائي وفق الشروط المنظمة لكل نوع شحنة. تحتفظ الشركة بحقها في رفض شحن أي محتوى ممنوع قانوناً أو لا يتوافق مع سياسات السلامة المعتمدة.' },
    t3title: { en: 'Customer Data', ar: 'بيانات العميل' },
    t3text: { en: 'The customer must provide correct and complete data in all forms (name, phone, address, parcel description, etc.). The company is committed to the confidentiality and protection of customer data and uses it only to complete shipping operations and service support.', ar: 'يجب على العميل تقديم بيانات صحيحة وكاملة في جميع النماذج (الاسم، التليفون، العنوان، وصف الطرد، إلخ). الشركة تلتزم بسرية وحماية بيانات العملاء ولا تستخدمها إلا لإتمام عمليات الشحن ودعم الخدمة.' },
    t4title: { en: 'Fragile Parcels', ar: 'الطرود القابلة للكسر' },
    t4text: { en: 'The customer should accurately disclose if the parcel is fragile so it can be specially packaged and secured. The company is not responsible for damage to fragile parcels if not specified by the customer in the form.', ar: 'ينبغي للعميل الإفصاح بدقة إذا كان الطرد قابل للكسر ليتم تغليفه وتأمينه بشكل خاص. الشركة غير مسؤولة عن تلف الطرود القابلة للكسر إذا لم يتم تحديدها من قبل العميل في النموذج.' },
    t5title: { en: 'Tracking and Unique Code', ar: 'المتابعة والكود الفريد' },
    t5text: { en: 'The company provides the customer with an electronic tracking code for each shipment that can be used for tracking on the website. The customer is responsible for keeping the code and not sharing it except with authorized parties.', ar: 'تمنح الشركة العميل كود تتبع إلكتروني لكل شحنة يمكن عبره المتابعة على الموقع. العميل مسؤول عن حفظ الكود وعدم مشاركته إلا مع الجهات المخوّلة.' },
    t6title: { en: 'Payment', ar: 'الدفع والسداد' },
    t6text: { en: 'Payment of shipping fees is according to the specified mechanism and can be made in cash or electronically depending on the governorate. Any change in prices or fees will be notified to the customer in advance before executing the shipping process.', ar: 'دفع رسوم الشحن يكون وفق الآلية المحددة، ويمكن الدفع نقداً أو الكترونياً حسب كل محافظة. أي تغيير في الأسعار أو الرسوم يتم إخطار العميل به مسبقاً قبل تنفيذ عملية الشحن.' },
    t7title: { en: 'Limitation of Liability', ar: 'حدود المسؤولية' },
    t7text: { en: 'The company is not responsible for any prohibited or dangerous content, loss, or damage not correctly stated by the customer. Transportation disruptions beyond the company\'s control (weather conditions, force majeure) may affect delivery times, and the company is committed to notifying the customer immediately.', ar: 'لا تتحمل الشركة أية مسؤولية عن محتوى ممنوع أو خطر أو فقدان أو تلف لم يتم ذكره صحيحاً من العميل. اضطرابات النقل الخارجة عن إرادة الشركة (أحوال جوية، ظروف قهرية) قد تؤثر على مدة التوصيل، وتلتزم الشركة بإخطار العميل فوراً.' },
    t8title: { en: 'Intellectual Property', ar: 'الملكية الفكرية' },
    t8text: { en: 'All trademark rights, designs, and technologies related to the "THE FAST BIRD" website and services are reserved for the company and may not be used or reproduced without written permission.', ar: 'جميع حقوق العلامة التجارية والتصاميم والتقنيات الخاصة بموقع وخدمات “THE FAST BIRD” محفوظة للشركة ولا يجوز استخدامها أو إعادة إنتاجها بدون إذن خطي.' },
    t9title: { en: 'Amendments', ar: 'التعديلات' },
    t9text: { en: 'The company has the right to amend these terms at any time, and they will take effect immediately upon being published on the company\'s website. Your continued use of the site after the terms have been amended means you automatically agree to them.', ar: 'للشركة الحق في تعديل هذه الشروط في أي وقت وتدخل حيز التطبيق فور نشرها على موقع الشركة. استمرار استخدامك للموقع بعد تعديل الشروط يعني موافقتك عليها تلقائياً.' },
    t10title: { en: 'Communication and Support', ar: 'التواصل والدعم' },
    t10text: { en: 'For any inquiries regarding the terms or use, you can contact customer service via the chat window or the company\'s official email.', ar: 'لأي استفسار بخصوص الشروط أو الاستخدام يمكن التواصل مع خدمة العملاء عبر نافذة الشات أو الإيميل الرسمي للشركة.' },
  },
  privacy: {
    title: { en: 'Privacy Policy', ar: 'سياسة الخصوصية' },
    p1title: { en: 'Introduction', ar: 'مقدمة' },
    p1text: { en: 'At THE FAST BIRD, we are committed to protecting the privacy of our users and safeguarding their personal data with care and transparency. This policy aims to clarify how we collect, use, and protect your information on our website.', ar: 'نحن في THE FAST BIRD نلتزم بحماية خصوصية مستخدمينا وحماية بياناتهم الشخصية بكل عناية وشفافية. تهدف هذه السياسة إلى توضيح كيفية جمع واستخدام وحماية معلوماتك على موقعنا.' },
    p2title: { en: 'Data We Collect', ar: 'البيانات التي نجمعها' },
    p2text: { en: 'Personal identification information (name, phone number, address, email)\nParcel and shipment details (parcel type, recipients, delivery addresses)\nInteraction data with the site (chat usage, pages visited, shipping tracking code)\nTechnical data such as IP address and device type used', ar: 'معلومات الهوية الشخصية (الاسم، رقم الهاتف، العنوان، البريد الإلكتروني)\nتفاصيل الطرود والشحنات (نوع الطرد، الجهات المستقبلة، عناوين التسليم)\nبيانات التفاعل مع الموقع (استخدام الدردشة، الصفحات التي تزورها، الكود الخاص بمتابعة الشحن)\nبيانات تقنية مثل عنوان الـ IP ونوع الجهاز المستخدم' },
    p3title: { en: 'How We Use Information', ar: 'كيفية استخدام المعلومات' },
    p3text: { en: 'To efficiently execute shipping and delivery requests\nTo improve our service and user experience\nTo communicate with the customer to confirm or follow up on orders\nTo provide technical support and respond to inquiries via chat or email\nTo enhance site security against unauthorized use', ar: 'تنفيذ طلبات الشحن والتوصيل بكفاءة\nتحسين الخدمة وتجربة المستخدم\nالتواصل مع العميل من أجل تأكيد الطلب أو المتابعة\nتوفير الدعم الفني والرد على الاستفسارات عبر الدردشة أو الإيميل\nتعزيز حماية الموقع من أي استخدام غير مصرح به' },
    p4title: { en: 'Data Protection', ar: 'حماية البيانات' },
    p4text: { en: 'We use the latest security technologies to secure your data against unauthorized access, modification, or loss. Customer data is not shared with any third party outside the company except when necessary, such as for the actual execution of the shipping service.', ar: 'نستخدم أحدث تقنيات الحماية لتأمين بياناتكم ضد الوصول غير المصرح به أو التعديل أو الفقد. بيانات العميل لا تُشارك مع أي طرف ثالث خارج الشركة إلا للضرورة، مثل التنفيذ الفعلي لخدمة الشحن.' },
    p5title: { en: 'Third-Party Disclosure', ar: 'الإفصاح لطرف ثالث' },
    p5text: { en: 'We do not sell or rent any personal data to third parties. We may share data only with shipping service providers or technical support if it is necessary to complete the service or under legal instructions.', ar: 'لا نبيع أو نؤجر أي بيانات شخصية للغير. قد نشارك البيانات فقط مع مزودي خدمات الشحن أو الدعم الفني إذا كان ذلك ضرورياً لإتمام الخدمة أو بموجب تعليمات قانونية.' },
    p6title: { en: 'Cookies', ar: 'ملفات تعريف الارتباط (Cookies)' },
    p6text: { en: 'The site uses cookies to improve the user experience and for technical and statistical purposes only. The customer can control cookie settings through their internet browser.', ar: 'يستخدم الموقع ملفات كوكيز لتحسين تجربة المستخدم ولأغراض فنية وإحصائية فقط. يمكن للعميل التحكم في إعدادات الكوكيز من خلال متصفح الإنترنت الخاص به.' },
    p7title: { en: 'Your Rights', ar: 'حقوقك' },
    p7text: { en: 'The customer has the right to request the correction or deletion of their data at any time. The customer can contact us via the official email to request modification or inquire about their data.', ar: 'يحق للعميل طلب تصحيح أو حذف بياناته في أي وقت. يمكن للعميل التواصل معنا عبر الإيميل الرسمي لطلب تعديل أو الاستفسار عن بياناته.' },
    p8title: { en: 'Changes to the Policy', ar: 'التغييرات على السياسة' },
    p8text: { en: 'We reserve the right to modify the privacy policy at any time, and the changes become effective immediately upon being published on the site. Customers are advised to review the policy periodically.', ar: 'نحن نحتفظ بحق تعديل سياسة الخصوصية في أي وقت، وتصبح التغييرات سارية فور نشرها على الموقع. يُنصح العملاء بمراجعة السياسة بشكل دوري.' },
    p9title: { en: 'Contact Us', ar: 'التواصل معنا' },
    p9text: { en: 'To inquire, request modification, or delete your data, please contact customer service via the official email or the chat window on the site.', ar: 'للاستفسار أو طلب تعديل أو حذف بياناتك، يرجى التواصل مع خدمة العملاء عبر الإيميل الرسمي أو نافذة الدردشة على الموقع.' },
  },
  contact: {
    title: { en: 'Contact Us', ar: 'اتصل بنا' },
    subtitle: { en: 'We are happy to receive all your inquiries and requests throughout the week!', ar: 'يسعدنا استقبال جميع استفساراتك وطلباتك على مدار الأسبوع!' },
    detailsTitle: { en: 'Contact Information', ar: 'بيانات التواصل' },
    adminTitle: { en: 'Administration', ar: 'الإدارة' },
    adminText: { en: '6th of October City', ar: 'مدينة السادس من أكتوبر' },
    mainCenterTitle: { en: 'Main Center', ar: 'المركز الرئيسي' },
    mainCenterText: { en: '3, 6th October St - El Wadi', ar: '3 شارع 6 أكتوبر - الوادي' },
    mainWarehouseTitle: { en: 'Main Warehouse', ar: 'المخزن الرئيسي' },
    mainWarehouseText: { en: '6th October St - El Wadi', ar: 'شارع 6 أكتوبر - الوادي' },
    emailTitle: { en: 'Email', ar: 'البريد الإلكتروني' },
    emailText: { en: 'shepping@thefastbird.com', ar: 'shepping@thefastbird.com' },
    phoneTitle: { en: 'Customer Service Phone', ar: 'هاتف خدمة العملاء' },
    phoneText: { en: '01500504070', ar: '01500504070' },
    hoursTitle: { en: 'Working Hours', ar: 'ساعات العمل' },
    hoursText: { en: 'Daily: 9:00 AM - 6:00 PM', ar: 'يومياً: 9:00 صباحاً - 6:00 مساءً' },
    hoursNote: { en: 'No holidays! Shipping all the time!', ar: 'مفيش أجازات! في شحن على طول!' },
    formTitle: { en: 'Message Us Directly', ar: 'راسلنا مباشرة' },
    formName: { en: 'Name', ar: 'الاسم' },
    formEmail: { en: 'Email', ar: 'البريد الإلكتروني' },
    formPhone: { en: 'Phone Number', ar: 'رقم الهاتف' },
    formMessage: { en: 'Your Message/Inquiry', ar: 'رسالتك/استفسارك' },
    formSubmit: { en: 'Send', ar: 'إرسال' },
    formError: { en: 'Oops! There was a problem submitting your form', ar: 'عفواً! حدثت مشكلة أثناء إرسال رسالتك' },
    chatTitle: { en: 'Or contact us via Quick Chat', ar: 'أو تواصل معنا عبر الدردشة السريعة' },
    chatText: { en: 'You can also speak to us directly via the "Sha\'a the Smart Bird" window on the site for any urgent inquiry!', ar: 'يمكنك أيضاً التحدث معنا مباشرة عبر نافذة "شعاع الطائر الذكي" على الموقع لأي استفسار عاجل!' },
    note: { en: 'Note: All customer data is confidential and is only used for the purpose of providing support and improving the service.', ar: 'ملاحظة: كل بيانات العملاء سرية ولا يتم استخدامها إلا بغرض تقديم الدعم وتحسين الخدمة.' },
    modalTitle: { en: 'Message Sent!', ar: 'تم إرسال الرسالة!' },
    modalText: { en: 'Thank you for choosing The Fast Bird! We will get back to you as soon as possible.', ar: 'شكراً على إختيارك الطائر السريع! سوف نقوم بالرد في أسرع وقت ممكن.' },
  },
  orderNow: {
    title: { en: 'Place a New Order', ar: 'اطلب شحنة جديدة' },
    subtitle: { en: 'Fill out the form below to start shipping with The Fast Bird.', ar: 'املأ النموذج أدناه لبدء الشحن مع الطائر السريع.' },
    senderInfo: { en: 'Sender Information', ar: 'بيانات المرسل' },
    name: { en: 'Full Name', ar: 'الاسم بالكامل' },
    phone: { en: 'Phone Number', ar: 'رقم التليفون' },
    address: { en: 'Address', ar: 'العنوان' },
    orderInfo: { en: 'Order Information', ar: 'بيانات الأوردر' },
    orderType: { en: 'Order Type', ar: 'نوع الأوردر' },
    selectType: { en: 'Select a type...', ar: 'اختر نوع...' },
    types: {
      wood: { en: 'Wood', ar: 'خشب' },
      glass: { en: 'Glass', ar: 'زجاج' },
      clothes: { en: 'Clothes', ar: 'ملابس' },
      tablets: { en: 'Tablets', ar: 'أجهزة لوحية' },
      electrical: { en: 'Electrical Appliances', ar: 'أجهزة كهربائية' },
      other: { en: 'Other', ar: 'أخرى' },
    },
    otherType: { en: 'Please specify', ar: 'برجاء التحديد' },
    weight: { en: 'Approximate Weight (kg)', ar: 'الوزن التقريبي (كجم)' },
    recipientInfo: { en: 'Recipient Information', ar: 'بيانات المرسل إليه' },
    recipientName: { en: 'Recipient Name', ar: 'اسم المرسل إليه' },
    recipientPhone: { en: 'Recipient Phone', ar: 'رقم تليفون المرسل إليه' },
    recipientAddress: { en: 'Recipient Address', ar: 'عنوان المرسل إليه' },
    submit: { en: 'Submit Order', ar: 'إرسال الطلب' },
    submitting: { en: 'Submitting...', ar: 'جاري الإرسال...' },
    submitError: { en: 'Failed to submit order. Please try again.', ar: 'فشل إرسال الطلب. برجاء المحاولة مرة أخرى.' },
    modalTitle: { en: 'Thank You!', ar: 'شكرًا لك!' },
    modalText: { en: 'Thank you for choosing to ship with The Fast Bird!', ar: 'شكرًا لاختيارك الشحن مع الطائر السريع!' },
    modalKeepCode: { en: 'Please keep the code to track your order.', ar: 'الرجاء الاحتفاظ بالكود لمتابعة الطلب.' },
    modalCopy: { en: 'Copy Code', ar: 'نسخ الكود' },
    modalCopied: { en: 'Copied!', ar: 'تم النسخ!' },
    modalCopyError: { en: 'Failed to copy', ar: 'فشل النسخ' },
    calculator: {
      title: { en: 'Estimate Shipping Cost', ar: 'تقدير تكلفة الشحن' },
      fromLabel: { en: 'From', ar: 'من' },
      weightLabel: { en: 'Weight (kg)', ar: 'الوزن (كجم)' },
      destinationLabel: { en: 'Destination', ar: 'الوجهة' },
      serviceTypeLabel: { en: 'Service Type', ar: 'نوع الخدمة' },
      calculateButton: { en: 'Calculate', ar: 'احسب' },
      resultTitle: { en: 'Estimated Cost', ar: 'التكلفة التقديرية' },
      currency: { en: 'EGP', ar: 'جنيه' },
      error: { en: 'Please fill in all fields.', ar: 'يرجى ملء جميع الحقول.' },
      destinations: [
        { value: 'cairo', name: { en: 'Cairo', ar: 'القاهرة' } },
        { value: 'giza', name: { en: 'Giza', ar: 'الجيزة' } },
        { value: 'alexandria', name: { en: 'Alexandria', ar: 'الإسكندرية' } },
        { value: 'tanta', name: { en: 'Tanta', ar: 'طنطا' } },
        { value: 'mansoura', name: { en: 'Mansoura', ar: 'المنصورة' } },
      ],
      serviceTypes: [
        { value: 'standard', name: { en: 'Standard (2-3 days)', ar: 'عادي (2-3 أيام)' } },
        { value: 'express', name: { en: 'Express (24 hours)', ar: 'سريع (24 ساعة)' } }
      ],
    } as CalculatorContent,
  },
  trackOrder: {
    title: { en: 'Track Your Shipment', ar: 'تتبع شحنتك' },
    subtitle: { en: 'Enter your tracking code below to see the latest updates.', ar: 'أدخل كود التتبع الخاص بك أدناه لرؤية آخر التحديثات.' },
    placeholder: { en: 'Enter tracking code (e.g., TKT123456)', ar: 'أدخل كود التتبع (مثال: TKT123456)' },
    button: { en: 'Track', ar: 'تتبع' },
    errorNotFound: { en: 'Tracking code not found. Please check the code and try again.', ar: 'لم يتم العثور على كود التتبع. يرجى التحقق من الكود والمحاولة مرة أخرى.' },
    errorInvalid: { en: 'Invalid tracking code format. It must be TKT followed by 6 digits.', ar: 'صيغة كود التتبع غير صالحة. يجب أن تكون TKT متبوعة بستة أرقام.' },
    loading: { en: 'Searching for your shipment...', ar: 'جاري البحث عن شحنتك...' },
    statusTitle: { en: 'Shipment Status', ar: 'حالة الشحنة' },
    statusPlaced: { en: 'Order Placed', ar: 'تم استلام الطلب' },
    statusWarehouse: { en: 'Processing at Warehouse', ar: 'قيد التجهيز في المخزن' },
    statusTransit: { en: 'In Transit', ar: 'قيد التوصيل' },
    statusDelivery: { en: 'Out for Delivery', ar: 'خرجت للتسليم' },
    statusDelivered: { en: 'Delivered', ar: 'تم التسليم' },
    firstTrackMessage: { en: 'Shipment is on its way to the warehouse', ar: 'الشحنة في طريقها للمستودع' },
    adminControlsTitle: { en: 'Admin Controls', ar: 'تحكم المشرف' },
    adminControlsDesc: { en: 'Set or update a custom message for this tracking code. This message will be shown to the user in a pop-up on their next search.', ar: 'قم بتعيين أو تحديث رسالة مخصصة لكود التتبع هذا. ستظهر هذه الرسالة للمستخدم في نافذة منبثقة في بحثه التالي.' },
    adminMessageLabel: { en: 'Custom Status Message', ar: 'رسالة الحالة المخصصة' },
    adminMessagePlaceholder: { en: 'e.g., Your shipment is delayed due to weather conditions.', ar: 'مثال: تأخرت شحنتك بسبب الأحوال الجوية.' },
    adminSaveButton: { en: 'Save Message', ar: 'حفظ الرسالة' },
    adminSaveSuccess: { en: 'Message updated successfully!', ar: 'تم تحديث الرسالة بنجاح!' },
  },
  chatbot: {
    toggle: { en: 'Toggle Chat', ar: 'فتح/إغلاق المحادثة' },
    name: { en: 'Sha\'a', ar: 'شعاع' },
    tagline: { en: 'Your Smart Assistant', ar: 'مساعدك الذكي' },
    placeholder: { en: 'Type your message...', ar: 'اكتب رسالتك...' },
    welcome: { en: 'Welcome to THE FAST BIRD!', ar: 'مرحباً بك في THE FAST BIRD' },
    askName: { en: 'I am "Sha\'a", your smart bird to help with any inquiry. What is your name?', ar: 'أنا "شعاع"، طائرك الذكي لمساعدتك في أي استفسار. اسمك إيه؟' },
    hello: { en: 'Welcome,', ar: 'أهلاً بك يا' },
    howHelp: { en: 'How can I assist you?', ar: 'أقدر أساعدك إزاي؟' },
    priceInquiry: { en: 'One of our representatives will contact you, {name}, as soon as possible. Or you can place your order through the following form: [Order Now]', ar: 'سوف يقوم أحد مسئولينا بالتواصل معك يا {name} في أقرب وقت. أو يمكنك طلب شحنتك من خلال الفورم التالي: [اطلب الآن]' },
    error: { en: 'I seem to be having some trouble. Please try again later.', ar: 'يبدو أنني أواجه بعض المشاكل. برجاء المحاولة مرة أخرى لاحقًا.' },
    settings: { en: 'Settings', ar: 'الإعدادات' },
    voice: { en: 'Voice', ar: 'الصوت' },
    speechRate: { en: 'Speech Rate', ar: 'سرعة الكلام' },
    speechRateNote: { en: 'Note: Rate adjustment is not currently supported by the API.', ar: 'ملاحظة: تعديل السرعة غير مدعوم حاليًا.' },
  },
  cookieConsent: {
    message: { en: 'We use cookies to enhance your browsing experience and analyze our traffic. By clicking "Accept", you consent to our use of cookies.', ar: 'نحن نستخدم ملفات تعريف الارتباط لتحسين تجربة التصفح الخاصة بك وتحليل حركة المرور لدينا. بالنقر على "قبول"، فإنك توافق على استخدامنا لملفات تعريف الارتباط.' },
    accept: { en: 'Accept', ar: 'قبول' },
    decline: { en: 'Decline', ar: 'رفض' },
  },
  footer: {
    credit: { en: 'Designed and Development by: ', ar: 'تصميم وتطوير: ' },
  }
};